In [3]:
# now first we download yfinace data for nse stocks data of past 5 years let see ddo we have not not 
import yfinance as yf # we dont have so we will download

ModuleNotFoundError: No module named 'yfinance'

In [ ]:
pip install yfinance  sqlalchemy pymysql openpyxl

Requirement already satisfied: yfinance in c:\new folder\anaconda\lib\site-packages (1.3.0)
Requirement already satisfied: sqlalchemy in c:\new folder\anaconda\lib\site-packages (1.4.39)
Requirement already satisfied: pymysql in c:\new folder\anaconda\lib\site-packages (1.1.3)
Requirement already satisfied: openpyxl in c:\new folder\anaconda\lib\site-packages (3.0.10)
Requirement already satisfied: pandas>=1.3.0 in c:\new folder\anaconda\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\new folder\anaconda\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\new folder\anaconda\lib\site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in c:\new folder\anaconda\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\new folder\anaconda\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\new folder\anaconda\lib\site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in c:\new folder\anaconda\lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\new folder\anaconda\lib\site-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\new folder\anaconda\lib\site-packages (from yfinance) (4.12.2)
Requirement already satisfied: curl_cffi>=0.15 in c:\new folder\anaconda\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\new folder\anaconda\lib\site-packages (from yfinance) (3.20.3)
Requirement already satisfied: websockets>=13.0 in c:\new folder\anaconda\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\new folder\anaconda\lib\site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: et_xmlfile in c:\new folder\anaconda\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: soupsieve>1.2 in c:\new folder\anaconda\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: cffi>=2.0.0 in c:\new folder\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\new folder\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.4.22)
Requirement already satisfied: rich in c:\new folder\anaconda\lib\site-packages (from curl_cffi>=0.15->yfinance) (13.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\new folder\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\new folder\anaconda\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\new folder\anaconda\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\new folder\anaconda\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\new folder\anaconda\lib\site-packages (from requests>=2.31->yfinance) (1.26.16)
Requirement already satisfied: pycparser in c:\new folder\anaconda\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\new folder\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\new folder\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\new folder\anaconda\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\new folder\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# importing all important library 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from datetime import timedelta, datetime
import yfinance as yf

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np

stocks = {
    'TCS': ('TCS.NS', 'IT'),
    'Infosys': ('INFY.NS', 'IT'),
    'HDFC Bank': ('HDFCBANK.NS', 'Banking'),
    'ICICI Bank': ('ICICIBANK.NS', 'Banking'),
    'Reliance': ('RELIANCE.NS', 'Energy'),
    'ONGC': ('ONGC.NS', 'Energy'),
    'HUL': ('HINDUNILVR.NS', 'FMCG'),
    'ITC': ('ITC.NS', 'FMCG'),
    'Sun Pharma': ('SUNPHARMA.NS', 'Pharma'),
    'Dr Reddys': ('DRREDDY.NS', 'Pharma')
}

all_data = []

for name, (ticker, sector) in stocks.items():
    print(f"Downloading {name}...")
    df = yf.download(ticker, start="2020-01-01", end="2024-12-31", auto_adjust=True)
    
    # Flatten any MultiIndex columns
    df.columns = df.columns.get_level_values(0)
    
    # Keep only OHLCV columns
    df = df[['Open', 'High', 'Low', 'Close', 'Volume']].copy()
    
    # Add metadata
    df['Stock'] = name
    df['Ticker'] = ticker
    df['Sector'] = sector
    
    all_data.append(df)

# Stack vertically
df_raw = pd.concat(all_data, axis=0)
df_raw.reset_index(inplace=True)
df_raw.rename(columns={'index': 'Date'}, inplace=True)

print(f"\n✅ Total records: {len(df_raw)}")
print(f"✅ Columns: {df_raw.columns.tolist()}")
print(df_raw.head(10))

Downloading TCS...

[*********************100%***********************]  1 of 1 completed

Downloading Infosys...

[*********************100%***********************]  1 of 1 completed

Downloading HDFC Bank...

[*********************100%***********************]  1 of 1 completed

Downloading ICICI Bank...

[*********************100%***********************]  1 of 1 completed

Downloading Reliance...

[*********************100%***********************]  1 of 1 completed

Downloading ONGC...

[*********************100%***********************]  1 of 1 completed

Downloading HUL...

[*********************100%***********************]  1 of 1 completed

Downloading ITC...

[*********************100%***********************]  1 of 1 completed

Downloading Sun Pharma...

[*********************100%***********************]  1 of 1 completed

Downloading Dr Reddys...

[*********************100%***********************]  1 of 1 completed

✅ Total records: 12370
✅ Columns: ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Stock', 'Ticker', 'Sector']
Price       Date         Open         High          Low        Close   Volume  \
0     2020-01-01  1866.458050  1880.146473  1854.405277  1866.113770  1354908
1     2020-01-02  1876.746243  1876.746243  1850.273183  1857.547852  2380752
2     2020-01-03  1863.014537  1913.808372  1863.014537  1894.566895  4655761
3     2020-01-06  1898.312091  1916.348167  1883.590403  1894.394897  3023209
4     2020-01-07  1894.437979  1906.619807  1880.060782  1899.043945  2429317
5     2020-01-08  1898.312143  1945.662333  1895.772493  1941.572998  5197454
6     2020-01-09  1935.976505  1938.731382  1902.616154  1906.361206  3734173
7     2020-01-10  1918.112995  1923.278470  1900.894745  1905.672852  1915807
8     2020-01-13  1909.374800  1910.321677  1880.835425  1885.699707  2843893
9     2020-01-14  1889.702615  1919.662407  1889.702615  1899.947388  2948452

Price Stock  Ticker Sector
0       TCS  TCS.NS     IT
1       TCS  TCS.NS     IT
2       TCS  TCS.NS     IT
3       TCS  TCS.NS     IT
4       TCS  TCS.NS     IT
5       TCS  TCS.NS     IT
6       TCS  TCS.NS     IT
7       TCS  TCS.NS     IT
8       TCS  TCS.NS     IT
9       TCS  TCS.NS     IT

In [ ]:
df_raw.head(20)

Price,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector
0,2020-01-01,1866.458050,1880.146473,1854.405277,1866.113770,1354908,TCS,TCS.NS,IT
1,2020-01-02,1876.746243,1876.746243,1850.273183,1857.547852,2380752,TCS,TCS.NS,IT
2,2020-01-03,1863.014537,1913.808372,1863.014537,1894.566895,4655761,TCS,TCS.NS,IT
3,2020-01-06,1898.312091,1916.348167,1883.590403,1894.394897,3023209,TCS,TCS.NS,IT
4,2020-01-07,1894.437979,1906.619807,1880.060782,1899.043945,2429317,TCS,TCS.NS,IT
5,2020-01-08,1898.312143,1945.662333,1895.772493,1941.572998,5197454,TCS,TCS.NS,IT
6,2020-01-09,1935.976505,1938.731382,1902.616154,1906.361206,3734173,TCS,TCS.NS,IT
7,2020-01-10,1918.112995,1923.278470,1900.894745,1905.672852,1915807,TCS,TCS.NS,IT
8,2020-01-13,1909.374800,1910.321677,1880.835425,1885.699707,2843893,TCS,TCS.NS,IT
9,2020-01-14,1889.702615,1919.662407,1889.702615,1899.947388,2948452,TCS,TCS.NS,IT
10,2020-01-15,1905.199294,1920.695719,1889.014098,1917.165894,2620681,TCS,TCS.NS,IT
11,2020-01-16,1917.209113,1936.192276,1906.921251,1927.411011,3117214,TCS,TCS.NS,IT
12,2020-01-17,1929.089475,1940.109196,1905.199156,1910.450806,3281059,TCS,TCS.NS,IT
13,2020-01-20,1889.616925,1930.338132,1856.299650,1868.481689,5817599,TCS,TCS.NS,IT
14,2020-01-21,1868.137141,1882.428373,1857.892365,1869.084229,1902980,TCS,TCS.NS,IT
15,2020-01-22,1877.649842,1902.616300,1871.365140,1899.947388,1773686,TCS,TCS.NS,IT
16,2020-01-23,1906.764279,1913.624032,1884.243357,1890.499146,2069866,TCS,TCS.NS,IT
17,2020-01-24,1890.499065,1890.499065,1872.422037,1883.984375,1319430,TCS,TCS.NS,IT
18,2020-01-27,1889.420743,1892.656496,1868.107960,1871.775146,1549101,TCS,TCS.NS,IT
19,2020-01-28,1875.874393,1887.782010,1856.891304,1884.287354,1743024,TCS,TCS.NS,IT

In [ ]:
df_raw.columns.name = None

# Also rename index col if it crept in
if 'Price' in df_raw.columns:
    df_raw.drop(columns=['Price'], inplace=True)

# Verify clean columns
print(f"✅ Columns: {df_raw.columns.tolist()}")
print(f"✅ Total Records: {len(df_raw)}")
print(f"✅ Stocks: {df_raw['Stock'].unique()}")
print(f"✅ Date range: {df_raw['Date'].min()} to {df_raw['Date'].max()}")
print(df_raw.head(5))

✅ Columns: ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Stock', 'Ticker', 'Sector']
✅ Total Records: 12370
✅ Stocks: ['TCS' 'Infosys' 'HDFC Bank' 'ICICI Bank' 'Reliance' 'ONGC' 'HUL' 'ITC'
 'Sun Pharma' 'Dr Reddys']
✅ Date range: 2020-01-01 00:00:00 to 2024-12-30 00:00:00
        Date         Open         High          Low        Close   Volume  \
0 2020-01-01  1866.458050  1880.146473  1854.405277  1866.113770  1354908
1 2020-01-02  1876.746243  1876.746243  1850.273183  1857.547852  2380752
2 2020-01-03  1863.014537  1913.808372  1863.014537  1894.566895  4655761
3 2020-01-06  1898.312091  1916.348167  1883.590403  1894.394897  3023209
4 2020-01-07  1894.437979  1906.619807  1880.060782  1899.043945  2429317

  Stock  Ticker Sector
0   TCS  TCS.NS     IT
1   TCS  TCS.NS     IT
2   TCS  TCS.NS     IT
3   TCS  TCS.NS     IT
4   TCS  TCS.NS     IT

In [ ]:
df_raw.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector
0,2020-01-01,1866.458050,1880.146473,1854.405277,1866.113770,1354908,TCS,TCS.NS,IT
1,2020-01-02,1876.746243,1876.746243,1850.273183,1857.547852,2380752,TCS,TCS.NS,IT
2,2020-01-03,1863.014537,1913.808372,1863.014537,1894.566895,4655761,TCS,TCS.NS,IT
3,2020-01-06,1898.312091,1916.348167,1883.590403,1894.394897,3023209,TCS,TCS.NS,IT
4,2020-01-07,1894.437979,1906.619807,1880.060782,1899.043945,2429317,TCS,TCS.NS,IT

In [ ]:
df_raw.value_counts('Sector')

Sector
Banking    2474
Energy     2474
FMCG       2474
IT         2474
Pharma     2474
Name: count, dtype: int64

In [ ]:
df_raw.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Stock     0
Ticker    0
Sector    0
dtype: int64

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12370 entries, 0 to 12369
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    12370 non-null  datetime64[ns]
 1   Open    12370 non-null  float64
 2   High    12370 non-null  float64
 3   Low     12370 non-null  float64
 4   Close   12370 non-null  float64
 5   Volume  12370 non-null  int64
 6   Stock   12370 non-null  object
 7   Ticker  12370 non-null  object
 8   Sector  12370 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 869.9+ KB

In [ ]:
# converting the date columns in datetime
df_raw['Date'] = pd.to_datetime(df_raw['Date'])

In [ ]:
df_raw['Date'].dtype

dtype('<M8[ns]')

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12370 entries, 0 to 12369
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    12370 non-null  datetime64[ns]
 1   Open    12370 non-null  float64
 2   High    12370 non-null  float64
 3   Low     12370 non-null  float64
 4   Close   12370 non-null  float64
 5   Volume  12370 non-null  int64
 6   Stock   12370 non-null  object
 7   Ticker  12370 non-null  object
 8   Sector  12370 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 869.9+ KB

In [ ]:
# lets ee how much dublicate where there b
before_dublicate = len(df_raw)
df_raw.drop_duplicates(inplace=True)
after_dublicate= len(df_raw)

In [ ]:
before_dublicate

12370

In [ ]:
after_dublicate

12370

In [ ]:
df_raw=df_raw.sort_values(by=['Stock','Date'])

In [ ]:
df_raw.head(10)

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma
11138,2020-01-08,553.641069,559.418193,551.907944,557.925781,1395115,Dr Reddys,DRREDDY.NS,Pharma
11139,2020-01-09,560.689166,565.503436,558.647920,562.403015,1877480,Dr Reddys,DRREDDY.NS,Pharma
11140,2020-01-10,564.232492,579.252992,563.298551,564.810181,5635735,Dr Reddys,DRREDDY.NS,Pharma
11141,2020-01-13,564.790863,571.261213,561.478643,568.988892,2209320,Dr Reddys,DRREDDY.NS,Pharma
11142,2020-01-14,569.008175,571.704154,564.617564,567.660156,1785850,Dr Reddys,DRREDDY.NS,Pharma

In [ ]:
# # 7. Add useful time columns like months, yer,month_name,quater 

df_raw['Year'] = df_raw['Date'].dt.year
df_raw['Month'] = df_raw['Date'].dt.month
df_raw['Month_Name'] =df_raw['Date'].dt.month_name()
df_raw['Quarter'] = df_raw['Date'].dt.quarter

In [ ]:
df_raw.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1

In [ ]:
df_raw['Quarter'].value_counts().sort_index(ascending=True)

Quarter
1    3070
2    3020
3    3190
4    3090
Name: count, dtype: int64

In [ ]:
df_raw['Month_Name'].value_counts().sort_index(ascending=True)

Month_Name
April         930
August       1050
December     1070
February     1000
January      1050
July         1080
June         1060
March        1020
May          1030
November     1000
October      1020
September    1060
Name: count, dtype: int64

In [ ]:
df_raw.describe()

,Date,Open,High,Low,Close,Volume,Year,Month,Quarter
count,12370,12370.000000,12370.000000,12370.000000,12370.000000,1.237000e+04,12370.000000,12370.000000,12370.000000
mean,2022-06-28 02:15:02.182700288,1142.583479,1153.803777,1130.720958,1142.076989,1.283396e+07,2021.987874,6.538399,2.509297
min,2020-01-01 00:00:00,39.788630,42.200059,33.492112,40.190533,1.041800e+05,2020.000000,1.000000,1.000000
25%,2021-03-26 00:00:00,520.201816,527.106785,512.365127,519.621460,2.676798e+06,2021.000000,4.000000,2.000000
50%,2022-06-27 00:00:00,906.098864,914.964087,897.773318,905.092743,8.347218e+06,2022.000000,7.000000,3.000000
75%,2023-09-25 00:00:00,1472.450733,1485.306441,1457.220631,1471.575195,1.682226e+07,2023.000000,9.000000,3.000000
max,2024-12-30 00:00:00,4332.652012,4348.038052,4272.055480,4311.585449,4.453421e+08,2024.000000,12.000000,4.000000
std,NaN,884.523992,892.203927,876.558621,884.279829,1.599514e+07,1.415076,3.450378,1.116231

In [ ]:
df_raw['Date'].min()

Timestamp('2020-01-01 00:00:00')

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12370 entries, 11133 to 1236
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        12370 non-null  datetime64[ns]
 1   Open        12370 non-null  float64
 2   High        12370 non-null  float64
 3   Low         12370 non-null  float64
 4   Close       12370 non-null  float64
 5   Volume      12370 non-null  int64
 6   Stock       12370 non-null  object
 7   Ticker      12370 non-null  object
 8   Sector      12370 non-null  object
 9   Year        12370 non-null  int32
 10  Month       12370 non-null  int32
 11  Month_Name  12370 non-null  object
 12  Quarter     12370 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(3), int64(1), object(4)
memory usage: 1.2+ MB

In [ ]:
# making daily return columns

df_raw['Daily_return'] = df_raw.groupby('Stock')['Close'].pct_change() * 100

In [ ]:
df_raw.head(10)

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter,Daily_return
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,NaN
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.503570
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.663194
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.175108
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.185853
11138,2020-01-08,553.641069,559.418193,551.907944,557.925781,1395115,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.452456
11139,2020-01-09,560.689166,565.503436,558.647920,562.403015,1877480,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.802478
11140,2020-01-10,564.232492,579.252992,563.298551,564.810181,5635735,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.428014
11141,2020-01-13,564.790863,571.261213,561.478643,568.988892,2209320,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.739843
11142,2020-01-14,569.008175,571.704154,564.617564,567.660156,1785850,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.233526

In [ ]:
df_raw['Volatility_30D'] =df_raw.groupby('Stock')['Daily_return'].transform(lambda x:x.rolling(window=30).std())

In [ ]:
# Explain STandrd deviation 

# we used Standard Deviateion beacuse see the value how much close to each other means 1,2,3,4 the vlaue is closed to each other that 
# mean risk low he and agar value are like 1 -3,2,5,-6 std is high that means risk is high 

df_raw.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter,Daily_return,Volatility_30D
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,NaN,NaN
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.503570,NaN
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.663194,NaN
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.175108,NaN
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.185853,NaN

In [ ]:
df_raw[df_raw['Stock']=='TCS'].head(60).groupby('Year')['Volatility_30D'].value_counts()

Year  Volatility_30D
2020  1.115790          1
      1.116480          1
      3.644713          1
      3.605384          1
      3.576070          1
      3.366991          1
      2.820689          1
      2.810034          1
      2.790328          1
      2.784918          1
      2.633390          1
      2.589912          1
      2.003616          1
      2.001190          1
      1.583196          1
      1.582498          1
      1.567993          1
      1.500147          1
      1.498664          1
      1.497145          1
      1.230455          1
      1.222070          1
      1.221263          1
      1.212501          1
      1.211163          1
      1.182329          1
      1.178732          1
      1.167654          1
      1.165579          1
      3.683865          1
Name: count, dtype: int64

In [ ]:
df_raw.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter,Daily_return,Volatility_30D
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,NaN,NaN
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.503570,NaN
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.663194,NaN
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.175108,NaN
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.185853,NaN

In [ ]:
df_raw['Year'].value_counts()

Year
2020    2510
2021    2480
2022    2480
2023    2450
2024    2450
Name: count, dtype: int64

In [ ]:
# EDA Exploratory data analysis 

# Part 1 — Stock wise Analysis
"""
Kaun sa stock sabse zyada grow kiya 2020-2024?
Kaun sa sabse risky raha?

"""
df_raw.groupby('Stock')

In [ ]:
df_raw.groupby('Stock')['Volatility_30D'].mean().reset_index()

        Stock  Volatility_30D
0   Dr Reddys        1.505724
1   HDFC Bank        1.551945
2         HUL        1.370860
3  ICICI Bank        1.719874
4         ITC        1.475148
5     Infosys        1.621656
6        ONGC        2.189952
7    Reliance        1.666048
8  Sun Pharma        1.493533
9         TCS        1.442440

In [ ]:
# we can clarliy see 6    ONGC    2.189953 hihly risky beacuise the std is high 

# now we will see the growth of stocks

Stock_Growth = df_raw.groupby('Stock')['Close'].agg(
    First_Price = 'first',
    last_Price = 'last'
).reset_index()

Stock_Growth['growth%'] = (Stock_Growth['last_Price'] - Stock_Growth['First_Price'])/Stock_Growth['First_Price']*100
Stock_Growth.sort_values(by='growth%', ascending=False)

        Stock  First_Price   last_Price     growth%
8  Sun Pharma   406.074005  1854.424316  356.671516
5     Infosys   633.151123  1851.214478  192.381141
6        ONGC    85.371399   216.396332  153.476380
4         ITC   173.395218   434.878693  150.802011
3  ICICI Bank   519.137939  1284.736938  147.475062
0   Dr Reddys   554.488342  1368.222534  146.754067
9         TCS  1866.113770  3947.244629  111.522185
7    Reliance   675.324158  1205.883789   78.563698
1   HDFC Bank   605.529297   877.094360   44.847552
2         HUL  1749.931396  2301.023438   31.492208

In [ ]:
# IT vs Banking vs Energy vs FMCG vs Pharma — kaun sa sector best performer?
best_performer = df_raw.groupby('Sector')['Close'].agg(
    first_price = 'first',
    last_price = 'last'
).reset_index()

best_performer['growth%'] = (best_performer['last_price'] - best_performer['first_price'])/best_performer['first_price']*100
best_performer.sort_values(by='growth%',ascending=False)

NameError: name 'df_raw' is not defined

In [ ]:
df_raw.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter,Daily_return,Volatility_30D
11133,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,NaN,NaN
11134,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.503570,NaN
11135,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.663194,NaN
11136,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.175108,NaN
11137,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.185853,NaN

In [ ]:
HUL=df_raw[df_raw['Stock']=='HUL']['Close'].agg(
    first_price = lambda x:x.iloc[0],
    last_price = lambda x:x.iloc[-1]
)

HUL['growth%'] = (HUL['last_price'] - HUL['first_price'])/HUL['first_price']*100
print(HUL)

first_price    1749.931396
last_price     2301.023438
growth%          31.492208
Name: Close, dtype: float64

In [ ]:
# first insights from the data
"""
Sun Pharma — 356% growth!

COVID ne pharma ko rocket bana diya 

Infosys — 192%

Digital boom post COVID

Surprising ones:

ONGC 153% — energy prices globally badhe
ITC 150% — cigarette company ne IT aur pharma ko peechhe chod diya 

 Conclusion:

Reliance sirf 78% — itni badi company, itna kam?
HDFC Bank 44% — banking sector struggle kiya
HUL sirf 31% — FMCG slowest
"""

'\n Sun Pharma — 356% growth!\n\nCOVID ne pharma ko rocket bana diya \n\n Infosys — 192%\n\nDigital boom post COVID\n\n Surprising ones:\n\nONGC 153% — energy prices globally badhe\nITC 150% — cigarette company ne IT aur pharma ko peechhe chod diya 😄\n\n😢 Disappointments:\n\nReliance sirf 78% — itni badi company, itna kam?\nHDFC Bank 44% — banking sector struggle kiya\nHUL sirf 31% — FMCG slowest\n'

In [ ]:
# Ab Part 2 — Time Analysis shuru karte hain!
# Sabse pehle socho — COVID crash March 2020 mein konsa mahina sabse bura tha?

df_raw[df_raw['Year']==2020].groupby('Month')['Daily_return'].mean().reset_index().sort_values(by='Daily_return',ascending = True)

    Month  Daily_return
2       3     -0.520303
1       2     -0.367360
0       1     -0.063647
4       5     -0.019266
8       9      0.006567
9      10      0.022021
7       8      0.045197
5       6      0.218523
6       7      0.371720
10     11      0.433907
11     12      0.437343
3       4      0.900399

In [ ]:
# Daily_Return column use karo — har stock ka — aur pivot karo pehle jisse har stock ek alag column ban jaye — phir .corr() lagao!

df_raw.pivot_table(index='Date',columns='Stock',values='Daily_return').corr()

Stock,Dr Reddys,HDFC Bank,HUL,ICICI Bank,ITC,Infosys,ONGC,Reliance,Sun Pharma,TCS
Stock,,,,,,,,,,
Dr Reddys,1.000000,0.155368,0.312621,0.168667,0.183893,0.281898,0.169619,0.262053,0.444383,0.259079
HDFC Bank,0.155368,1.000000,0.242370,0.639453,0.290478,0.357681,0.205527,0.441828,0.264501,0.313961
HUL,0.312621,0.242370,1.000000,0.252123,0.290888,0.328749,0.112443,0.322906,0.248938,0.318733
ICICI Bank,0.168667,0.639453,0.252123,1.000000,0.336612,0.377255,0.322507,0.438589,0.292685,0.335261
ITC,0.183893,0.290478,0.290888,0.336612,1.000000,0.247935,0.302578,0.305167,0.295039,0.243443
Infosys,0.281898,0.357681,0.328749,0.377255,0.247935,1.000000,0.242798,0.361304,0.284387,0.707710
ONGC,0.169619,0.205527,0.112443,0.322507,0.302578,0.242798,1.000000,0.393050,0.237649,0.264104
Reliance,0.262053,0.441828,0.322906,0.438589,0.305167,0.361304,0.393050,1.000000,0.317954,0.386882
Sun Pharma,0.444383,0.264501,0.248938,0.292685,0.295039,0.284387,0.237649,0.317954,1.000000,0.274967
TCS,0.259079,0.313961,0.318733,0.335261,0.243443,0.707710,0.264104,0.386882,0.274967,1.000000

In [ ]:
df_raw.to_csv('nse_stocks_2020_2024.csv', index=False)

In [5]:
import pandas as pd

data_2 = pd.read_csv('nse_stocks_2020_2024.csv')

In [6]:
data_2.head()

,Date,Open,High,Low,Close,Volume,Stock,Ticker,Sector,Year,Month,Month_Name,Quarter,Daily_return,Volatility_30D
0,2020-01-01,554.603880,556.240744,550.790957,554.488342,773895,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,NaN,NaN
1,2020-01-02,555.335723,556.991803,550.791021,551.696106,1494155,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.503570,NaN
2,2020-01-03,551.696027,557.877592,549.221486,555.354919,1723390,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.663194,NaN
3,2020-01-06,552.870759,558.031642,549.635583,554.382446,1788685,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,-0.175108,NaN
4,2020-01-07,556.529666,560.381082,552.880470,555.412781,1788175,Dr Reddys,DRREDDY.NS,Pharma,2020,1,January,1,0.185853,NaN

In [13]:
# finding best performer growth wise and converting it into new csv for bi report

Growths = data_2.groupby(['Stock','Sector'])['Close'].agg(
    first_price = 'first',
    last_price = "last"
).reset_index()

Growths['Growth%'] = (
    (Growths['last_price'] - Growths['first_price'])
    / Growths['first_price']
) * 100
Growths.sort_values(by='Growth%',ascending=False)

Growths.to_csv('stock_growths.csv',index=False)